# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.studentsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.studentsTable.setGeometry(QtCore.QRect(5, 31, 451, 471))
        self.studentsTable.setObjectName("studentsTable")
        self.studentsTable.setColumnCount(3)
        self.studentsTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setItem(1, 2, item)
        self.studentsTable.horizontalHeader().setVisible(True)
        self.studentsTable.horizontalHeader().setDefaultSectionSize(110)
        self.studentsTable.verticalHeader().setVisible(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 510, 441, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newEntryBTN = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.newEntryBTN.setObjectName("newEntryBTN")
        self.horizontalLayout.addWidget(self.newEntryBTN)
        self.saveBTN = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveBTN.setObjectName("saveBTN")
        self.horizontalLayout.addWidget(self.saveBTN)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.studentsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.studentsTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.studentsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vorname"))
        item = self.studentsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nachname"))
        item = self.studentsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Studienfach"))
        __sortingEnabled = self.studentsTable.isSortingEnabled()
        self.studentsTable.setSortingEnabled(False)
        item = self.studentsTable.item(0, 0)
        item.setText(_translate("MainWindow", "Max"))
        item = self.studentsTable.item(0, 1)
        item.setText(_translate("MainWindow", "Mustermann"))
        item = self.studentsTable.item(0, 2)
        item.setText(_translate("MainWindow", "Informatik"))
        item = self.studentsTable.item(1, 0)
        item.setText(_translate("MainWindow", "Erika"))
        item = self.studentsTable.item(1, 1)
        item.setText(_translate("MainWindow", "Musterfrau"))
        item = self.studentsTable.item(1, 2)
        item.setText(_translate("MainWindow", "Mathematik"))
        self.studentsTable.setSortingEnabled(__sortingEnabled)
        self.newEntryBTN.setText(_translate("MainWindow", "Neuer Eintrag"))
        self.saveBTN.setText(_translate("MainWindow", "Speichern"))
